In [2]:
import pandas as pd
df = pd.read_csv("../Data/raw/DataCoSupplyChainDataset.csv",encoding = "latin1")

## **Data Understanding**

In [3]:
print(df.shape)
df.head()

(180519, 53)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [4]:
df.tail()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [5]:
df.sample(5,random_state=42)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
80120,TRANSFER,5,4,11.090000,175.990005,Late delivery,1,48,Water Sports,Caguas,...,90036.0,1073,48,NaN,http://images.acmesports.sports/Pelican+Sunstr...,Pelican Sunstream 100 Kayak,199.990005,0,4/6/2016 21:05,Standard Class
19670,PAYMENT,2,1,9.800000,245.000000,Late delivery,1,24,Women's Apparel,Florissant,...,NaN,502,24,NaN,http://images.acmesports.sports/Nike+Men%27s+D...,Nike Men's Dri-FIT Victory Golf Polo,50.000000,0,6/11/2017 18:43,First Class
114887,TRANSFER,2,4,117.550003,244.899994,Advance shipping,0,46,Indoor/Outdoor Games,Carmichael,...,NaN,1014,46,NaN,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.980000,0,1/4/2015 14:32,Standard Class
120110,TRANSFER,5,4,118.430000,251.979996,Late delivery,1,43,Camping & Hiking,Troy,...,NaN,957,43,NaN,http://images.acmesports.sports/Diamondback+Wo...,Diamondback Women's Serene Classic Comfort Bi,299.980011,0,1/15/2017 1:46,Standard Class
56658,DEBIT,2,4,-21.590000,107.970001,Advance shipping,0,29,Shop By Sport,Caguas,...,NaN,627,29,NaN,http://images.acmesports.sports/Under+Armour+G...,Under Armour Girls' Toddler Spine Surge Runni,39.990002,0,4/8/2017 7:15,Standard Class

In [6]:
columns= pd.DataFrame({
    "Column Number":range(1, len(df.columns)+1),
    "Column Name": df.columns
})
columns

    Column Number                    Column Name
0               1                           Type
1               2       Days for shipping (real)
2               3  Days for shipment (scheduled)
3               4              Benefit per order
4               5             Sales per customer
5               6                Delivery Status
6               7             Late_delivery_risk
7               8                    Category Id
8               9                  Category Name
9              10                  Customer City
10             11               Customer Country
11             12                 Customer Email
12             13                 Customer Fname
13             14                    Customer Id
14             15                 Customer Lname
15             16              Customer Password
16             17               Customer Segment
17             18                 Customer State
18             19                Customer Street
19             20               Customer Zipcode
20             21                  Department Id
21             22                Department Name
22             23                       Latitude
23             24                      Longitude
24             25                         Market
25             26                     Order City
26             27                  Order Country
27             28              Order Customer Id
28             29        order date (DateOrders)
29             30                       Order Id
30             31         Order Item Cardprod Id
31             32            Order Item Discount
32             33       Order Item Discount Rate
33             34                  Order Item Id
34             35       Order Item Product Price
35             36        Order Item Profit Ratio
36             37            Order Item Quantity
37             38                          Sales
38             39               Order Item Total
39             40         Order Profit Per Order
40             41                   Order Region
41             42                    Order State
42             43                   Order Status
43             44                  Order Zipcode
44             45                Product Card Id
45             46            Product Category Id
46             47            Product Description
47             48                  Product Image
48             49                   Product Name
49             50                  Product Price
50             51                 Product Status
51             52     shipping date (DateOrders)
52             53                  Shipping Mode

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [27]:
df.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [13]:
missing = pd.DataFrame({
    "Missing Value": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum()/len(df)*100).round(2)
})

missing = missing[missing["Missing Value"] > 0]
missing.sort_values(by="Missing Percentage", ascending=False)

                     Missing Value  Missing Percentage
Product Description         180519              100.00
Order Zipcode               155679               86.24
Customer Lname                   8                0.00
Customer Zipcode                 3                0.00

In [24]:
df.duplicated().sum()

np.int64(0)

In [28]:
print(df["Order Id"].duplicated().sum())

114767

In [29]:
print(df["Customer Id"].duplicated().sum())

159867

In [25]:
unique = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": df.nunique().values
})

unique.sort_values("Unique Values")

                           Column  Unique Values
46            Product Description              0
50                 Product Status              1
15              Customer Password              1
11                 Customer Email              1
6              Late_delivery_risk              2
10               Customer Country              2
16               Customer Segment              3
0                            Type              4
52                  Shipping Mode              4
5                 Delivery Status              4
2   Days for shipment (scheduled)              4
36            Order Item Quantity              5
24                         Market              5
1        Days for shipping (real)              7
42                   Order Status              9
20                  Department Id             11
21                Department Name             11
32       Order Item Discount Rate             18
40                   Order Region             23
17                 Customer State             46
8                   Category Name             50
7                     Category Id             51
45            Product Category Id             51
49                  Product Price             75
34       Order Item Product Price             75
30         Order Item Cardprod Id            118
48                   Product Name            118
47                  Product Image            118
44                Product Card Id            118
35        Order Item Profit Ratio            162
26                  Order Country            164
37                          Sales            193
9                   Customer City            563
43                  Order Zipcode            609
12                 Customer Fname            782
19               Customer Zipcode            995
31            Order Item Discount           1017
41                    Order State           1089
14                 Customer Lname           1109
38               Order Item Total           2927
4              Sales per customer           2927
25                     Order City           3597
23                      Longitude           4487
18                Customer Street           7458
22                       Latitude          11250
27              Order Customer Id          20652
13                    Customer Id          20652
39         Order Profit Per Order          21998
3               Benefit per order          21998
51     shipping date (DateOrders)          63701
29                       Order Id          65752
28        order date (DateOrders)          65752
33                  Order Item Id         180519

## **Key Findings**

* The dataset contains 0 duplicate rows, indicating each row represent unique transaction.
* Product description have 100% missing values thus it contains no description about the products.This column will be excluded for further analysis.
* Order Zipcode have 86% missing values,making it unsuitable for meaningful analysis. It will also be removed from the analytical dataset.
* Customer Zipcode and Customer Last Name contains only a few missing values,which have minimal impact on overall analysis.
* A large number of duplicate Order id and Customer id is observed, which is expected since a customer can place multiple order at the same time similarly, a single customer order may contain multiple products, resulting in multiple records with the same Order ID.

## **Data Cleaning**

In [30]:
columns_to_drop= [
    "Product Description",
    "Order Zipcode",
    "Customer Email",
    "Customer Password",
    "Product Status"
]

df.drop(columns= columns_to_drop, inplace = True)

In [32]:
df.shape

(180519, 48)

In [33]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname',
       'Customer Segment', 'Customer State', 'Customer Street',
       'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude',
       'Longitude', 'Market', 'Order City', 'Order Country',
       'Order Customer Id', 'order date (DateOrders)', 'Order Id',
       'Order Item Cardprod Id', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Quantity', 'Sales',
       'Order Item Total', 'Order Profit Per Order', 'Order Region',
       'Order State', 'Order Status', 'Product Card Id', 'Product Category Id',
       'Product Image', 'Product Name', 'Product Price',
       'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

(Customer Email,Customer Password) These columns where dropped because they contained constant placeholder values ,
and product status column was dropped because it had constant value across all records.

In [39]:
df.to_csv('../Data/cleaned/DataCoSupplyChainDataset_cleaned.csv', index=False)

In [41]:
print("Cleaned dataset shape:", df.shape)

Cleaned dataset shape: (180519, 48)